# Ventorystack: Docker Compose
# https://docs.docker.com/compose/
#
# Usage: docker-compose up
version: '3'
services:
  chatbot:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    image: python:2.7.9
    ports:
      - "5000:5000"
    volumes:
    - .:/app
    restart: always
