# python-facebook-chatbot: Docker Compose
# https://docs.docker.com/compose/
#
# Usage: test up
version: '3'
services:

  app:
    environment: &environment
      - APP_NAME=python-facebook-chatbot
    build:
      context: .
      dockerfile: provision/docker/app-test/Dockerfile
